export function defaultData(): Object[] {
  return [
    {
      customerBillingRefNum: 'cbf01',
      orderId: '114961930',
      orderType: 'SM099',
      createdOn: '06/09/2019',
      description: 'LOCATE RETIC VALVE',
      operationDescription: 'WRCV0014 LOCATE RETICULATION MAIN VALVE',
      basicStartDate: '01/07/2018',
      basicStartTime: '',
      basicFinishDate: '01/23/2018',
      basicFinishTime: '',
      dueDays: '206',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Luke',
      lastName: 'McCormack',
      city: 'FORTITUDE VALLEY',
      street: '52A ALFRED ST',
      asset: 'AU-QUU-NRTH-4006',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes:
        'kiran \n jayanth \n murali \n chiru \n sanketh \n pavan \n',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/23/2021',
      requiredFinishTime: '',
      duration: '206',
      crewAllocation: '13061906',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RV114528',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: 'cbf02',
      orderId: '114961798',
      orderType: 'SM02',
      createdOn: '06/09/2019',
      description: 'LOCATE SCOUR VALVE',
      operationDescription: 'WRCV0015 LOCATE SCOUR VALVE',
      basicStartDate: '02/07/2019',
      basicStartTime: '',
      basicFinishDate: '01/24/2019',
      basicFinishTime: '',
      dueDays: '207',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Jake',
      lastName: 'Ngatuere',
      city: 'SPRING HILL',
      street: '83 ST PAULS TCE',
      asset: 'AU-QUU-NRTH-4000',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes:
        'kiran \n jayanth \n murali \n chiru \n sanketh \n pavan \n',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/23/2021',
      requiredFinishTime: '',
      duration: '206',
      crewAllocation: '13057225',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC16587',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: 'cbf03',
      orderId: '114962044',
      orderType: 'SM03',
      createdOn: '06/09/2019',
      description: 'LOCATE SCOUR VALVE',
      operationDescription: 'WRCV0015 LOCATE SCOUR VALVE',
      basicStartDate: '01/07/2020',
      basicStartTime: '',
      basicFinishDate: '01/23/2021',
      basicFinishTime: '',
      dueDays: '208',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Luke',
      lastName: 'McCormack',
      city: 'FORTITUDE VALLEY',
      street: '167 ALFRED ST',
      asset: 'AU-QUU-NRTH-4006',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes:
        'kiran \n jayanth \n murali \n chiru \n sanketh \n pavan \n',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/23/2021',
      requiredFinishTime: '',
      duration: '206',
      crewAllocation: '13061906',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC16635',
      subContractor: '',
      conflicts: false
    },

    {
      customerBillingRefNum: 'cbf04',
      orderId: '114962051',
      orderType: 'SM04',
      createdOn: '06/09/2019',
      description: 'LOCATE SCOUR VALVE',
      operationDescription: 'WRCV0015 LOCATE SCOUR VALVE',
      basicStartDate: '01/07/2020',
      basicStartTime: '',
      basicFinishDate: '01/23/2021',
      basicFinishTime: '',
      dueDays: '206',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Jake',
      lastName: 'Ngatuere',
      city: 'BRISBANE CITY',
      street: '205 NORTH QY',
      asset: 'AU-QUU-NRTH-4000',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes:
        'kiran \n jayanth \n murali \n chiru \n sanketh \n pavan \n',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/23/2021',
      requiredFinishTime: '',
      duration: '206',
      crewAllocation: '13057225',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC44561',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: 'cb05',
      orderId: '114962063',
      orderType: 'SM06',
      createdOn: '06/09/2019',
      description: 'LOCATE SCOUR VALVE',
      operationDescription: 'WRCV0015 LOCATE SCOUR VALVE',
      basicStartDate: '01/07/2020',
      basicStartTime: '',
      basicFinishDate: '01/23/2021',
      basicFinishTime: '',
      dueDays: '206',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Gary',
      lastName: 'Meredith',
      city: 'BRISBANE CITY',
      street: '175 GEORGE ST',
      asset: 'AU-QUU-NRTH-4000',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes:
        'kiran \n jayanth \n murali \n chiru \n sanketh \n pavan \n',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/23/2021',
      requiredFinishTime: '',
      duration: '206',
      crewAllocation: '13052219',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC44646',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01774130',
      orderId: '115794404',
      orderType: 'SM89',
      createdOn: '22/09/2020',
      description: 'MAINTAIN RETIC VALVE',
      operationDescription: 'WRCV0024 MAINT RETICULATION MAIN VALVE',
      basicStartDate: '01/10/2020',
      basicStartTime: '',
      basicFinishDate: '01/29/2021',
      basicFinishTime: '',
      dueDays: '120',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Ben',
      lastName: 'Brown',
      city: 'WYNNUM WEST',
      street: '17 GWYNNE ST',
      asset: 'AU-QUU-NRTH-4178',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/10/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/29/2021',
      requiredFinishTime: '',
      duration: '120',
      crewAllocation: '13057228',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RV20459',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01786470',
      orderId: '115794443',
      orderType: 'SM99',
      createdOn: '22/09/2020',
      description: 'Maintain Retic Scour Valve',
      operationDescription: 'WRCV0025 MAINTAIN SCOUR VALVE',
      basicStartDate: '01/10/2020',
      basicStartTime: '',
      basicFinishDate: '01/29/2021',
      basicFinishTime: '',
      dueDays: '120',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'BOONDALL',
      street: '15 CARDINAL ST',
      asset: 'AU-QUU-NRTH-4034',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/10/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/29/2021',
      requiredFinishTime: '',
      duration: '120',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC6064',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01784903',
      orderId: '115858649',
      orderType: 'SM01',
      createdOn: '26/10/2020',
      description: 'Maintain Retic Scour Valve',
      operationDescription: 'WRCV0025 MAINTAIN SCOUR VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/30/2021',
      basicFinishTime: '',
      dueDays: '90',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'KANGAROO POINT',
      street: '2/47 THOMAS ST',
      asset: 'AU-QUU-SOTH-4169',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/30/2021',
      requiredFinishTime: '',
      duration: '90',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC22862',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01793380',
      orderId: '115858724',
      orderType: 'SM02',
      createdOn: '26/10/2020',
      description: 'Maintain Retic Scour Valve',
      operationDescription: 'WRCV0025 MAINTAIN SCOUR VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/30/2021',
      basicFinishTime: '',
      dueDays: '90',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'CARINDALE',
      street: '5 HATHERTON CR',
      asset: 'AU-QUU-SOTH-4152',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/30/2021',
      requiredFinishTime: '',
      duration: '90',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC41526',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '02004272',
      orderId: '115858842',
      orderType: 'SM03',
      createdOn: '26/10/2020',
      description: 'Maintain Minor Fire Hydrant Uti',
      operationDescription: 'WRCV0017 MAINTAIN FIRE HYDRANT',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '91',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'UPPER MOUNT GRAVATT',
      street: '11 GRANBY ST',
      asset: 'AU-QUU-SOTH-4122',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '91',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY46775',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '02056359',
      orderId: '115966292',
      orderType: 'SM04',
      createdOn: '18/12/2020',
      description: 'Locate Retic Valve',
      operationDescription: 'WRCV0014 LOCATE RETICULATION MAIN VALVE',
      basicStartDate: '18/12/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '44',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'THE GAP',
      street: '965 WATERWORKS RD',
      asset: 'AU-QUU-NRTH-4061',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '18/12/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '44',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RV110689',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '02056358',
      orderId: '115966490',
      orderType: 'SM06',
      createdOn: '18/12/2020',
      description: 'Locate Retic Valve',
      operationDescription: 'WRCV0014 LOCATE RETICULATION MAIN VALVE',
      basicStartDate: '18/12/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '44',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'THE GAP',
      street: '12 GLEN AFFRIC ST',
      asset: 'AU-QUU-NRTH-4061',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '18/12/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '44',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RV17088',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '02005073',
      orderId: '115858814',
      orderType: 'SM89',
      createdOn: '26/10/2020',
      description: 'Inoperable scour',
      operationDescription: 'WRCV0025 MAINTAIN SCOUR VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '91',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'VIRGINIA',
      street: '2 MEADFOOT RD',
      asset: 'AU-QUU-NRTH-4014',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '91',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC8821',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01804227',
      orderId: '115858812',
      orderType: 'SM99',
      createdOn: '26/10/2020',
      description: 'Maintain Retic Scour Valve',
      operationDescription: 'WRCV0025 MAINTAIN SCOUR VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '91',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'CLAYFIELD',
      street: '58 BONNEY AV',
      asset: 'AU-QUU-NRTH-4011',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '91',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC12600',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01773242',
      orderId: '115858416',
      orderType: 'SM01',
      createdOn: '26/10/2020',
      description: 'Maintain Retic Scour Valve',
      operationDescription: 'WRCV0025 MAINTAIN SCOUR VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '91',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'VIRGINIA',
      street: '35 DOWNFALL RD',
      asset: 'AU-QUU-NRTH-4014',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '91',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RSC8717',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '02008812',
      orderId: '115858650',
      orderType: 'SM02',
      createdOn: '26/10/2020',
      description: 'Clean out valve pit',
      operationDescription: 'WRCV0024 MAINT RETICULATION MAIN VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '01/31/2021',
      basicFinishTime: '',
      dueDays: '91',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'CANNON HILL',
      street: '6 SOUTHGATE AV',
      asset: 'AU-QUU-SOTH-4170',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '01/31/2021',
      requiredFinishTime: '',
      duration: '91',
      crewAllocation: '13054822',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RV124139',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01822235',
      orderId: '132263146',
      orderType: 'SM01',
      createdOn: '24/08/2020',
      description: 'IM CAPITAL RENEW RETIC HYDRANT FAILURE',
      operationDescription: 'WRCV0056 IM Capital Retic Wtr',
      basicStartDate: '28/08/2020',
      basicStartTime: '',
      basicFinishDate: '02/28/2021',
      basicFinishTime: '',
      dueDays: '184',
      customerWorkType: 'AC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'KANGAROO POINT',
      street: '36 LEOPARD ST',
      asset: 'AU-QUU-SOTH-4169',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '28/08/2020',
      requiredStartTime: '',
      requiredFinishDate: '02/28/2021',
      requiredFinishTime: '',
      duration: '184',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY141105',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '01770677',
      orderId: '115057918',
      orderType: 'SM02',
      createdOn: '16/10/2019',
      description: 'MAINTAIN FIRE HYDRANT',
      operationDescription: 'WRCV0017 MAINTAIN FIRE HYDRANT',
      basicStartDate: '16/10/2019',
      basicStartTime: '',
      basicFinishDate: '02/28/2021',
      basicFinishTime: '',
      dueDays: '501',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Sean',
      lastName: 'Richards',
      city: 'SUNNYBANK',
      street: '88 MAINS RD',
      asset: 'AU-QUU-SOTH-4109',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '16/10/2019',
      requiredStartTime: '',
      requiredFinishDate: '02/28/2021',
      requiredFinishTime: '',
      duration: '501',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY53121',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '01764579',
      orderId: '115858532',
      orderType: 'SM03',
      createdOn: '26/10/2020',
      description: 'Maintain Reflux Valve',
      operationDescription: 'WRCV0022 MAINTAIN REFLUX VALVE',
      basicStartDate: '01/11/2020',
      basicStartTime: '',
      basicFinishDate: '03/01/2021',
      basicFinishTime: '',
      dueDays: '120',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Adam',
      lastName: 'Winney',
      city: 'BROOKFIELD',
      street: '23A CORNICHE PL',
      asset: 'AU-QUU-NRTH-4069',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/11/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/01/2021',
      requiredFinishTime: '',
      duration: '120',
      crewAllocation: '13047396',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RRV4663',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '01809895',
      orderId: '115602425',
      orderType: 'SM04',
      createdOn: '19/06/2020',
      description: 'Maintain Trunk Main Valve',
      operationDescription: 'WTCV0020 MAINT OF THE TRUNK MAIN VALVE',
      basicStartDate: '01/07/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '272',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Adam',
      lastName: 'Winney',
      city: 'TARRAGINDI',
      street: '140A WELLER RD',
      asset: 'AU-QUU-SOTH-4121',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '272',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'TV93714',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '02012773',
      orderId: '115724856',
      orderType: 'SM06',
      createdOn: '18/08/2020',
      description: 'Maintain Trunk Main Valve',
      operationDescription: 'WTCV0020 MAINT OF THE TRUNK MAIN VALVE',
      basicStartDate: '18/08/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '224',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Adam',
      lastName: 'Winney',
      city: 'KARALEE',
      street: '109-111 ELANORA WAY',
      asset: 'AU-QUU-SOTH-4306',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '18/08/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '224',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'TV300027',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '02012768',
      orderId: '115725026',
      orderType: 'SM89',
      createdOn: '18/08/2020',
      description: 'Maintain Trunk Main Valve',
      operationDescription: 'WTCV0020 MAINT OF THE TRUNK MAIN VALVE',
      basicStartDate: '18/08/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '224',
      customerWorkType: 'PC',
      customerPriority: 'A4',
      firstName: 'Farron',
      lastName: 'Swiec',
      city: 'BRACKEN RIDGE',
      street: '39B JUDE ST',
      asset: 'AU-QUU-NRTH-4017',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '18/08/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '224',
      crewAllocation: '13051713',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'TV93416',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '02023788',
      orderId: '132265618',
      orderType: 'SM99',
      createdOn: '14/09/2020',
      description: 'IM Cap Renew Retic Valve & Fitting Fail',
      operationDescription: 'WRCV0054 CIVIL INSP RETIC VALVE STATUS',
      basicStartDate: '14/09/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '197',
      customerWorkType: 'AC',
      customerPriority: 'A4',
      firstName: 'Farron',
      lastName: 'Swiec',
      city: 'HERSTON',
      street: '53 BRAMSTON TCE',
      asset: 'AU-QUU-NRTH-4006',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '14/09/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '197',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RV16606',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '01822556',
      orderId: '132264581',
      orderType: 'SM01',
      createdOn: '31/08/2020',
      description: 'IM CAPITAL RENEW RETIC HYDRANT FAILURE',
      operationDescription: 'WRCV0056 IM Capital Retic Wtr',
      basicStartDate: '01/07/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '272',
      customerWorkType: 'AC',
      customerPriority: 'A4',
      firstName: 'Farron',
      lastName: 'Swiec',
      city: 'AUCHENFLOWER',
      street: '424 MILTON RD',
      asset: 'AU-QUU-NRTH-4066',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '01/07/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '272',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY64037',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '01823001',
      orderId: '132265480',
      orderType: 'SM02',
      createdOn: '04/09/2020',
      description: 'IM CAPITAL RENEW RETIC HYDRANT FAILURE',
      operationDescription: 'WRCV0056 IM Capital Retic Wtr',
      basicStartDate: '04/09/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '207',
      customerWorkType: 'AC',
      customerPriority: 'A4',
      firstName: 'Farron',
      lastName: 'Swiec',
      city: 'AUCHENFLOWER',
      street: '2A RATHDONNELL ST',
      asset: 'AU-QUU-NRTH-4066',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '04/09/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '207',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY64129',
      subContractor: '',
      conflicts: true
    },
    {
      customerBillingRefNum: '01822926',
      orderId: '132265351',
      orderType: 'SM03',
      createdOn: '04/09/2020',
      description: 'IM CAPITAL RENEW RETIC HYDRANT FAILURE',
      operationDescription: 'WRCV0056 IM Capital Retic Wtr',
      basicStartDate: '04/09/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '207',
      customerWorkType: 'AC',
      customerPriority: 'A4',
      firstName: 'Farron',
      lastName: 'Swiec',
      city: 'AUCHENFLOWER',
      street: '7 RATHDONNELL ST',
      asset: 'AU-QUU-NRTH-4066',
      assetDescription: '',
      operationWorkCenter: '001CWI01',
      workCenterDescription: '',
      plannerGroup: '001',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '04/09/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '207',
      crewAllocation: '00000000',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY64078',
      subContractor: '',
      conflicts: false
    },
    {
      customerBillingRefNum: '01822515',
      orderId: '132264561',
      orderType: 'SM04',
      createdOn: '30/08/2020',
      description: 'IM CAPITAL RENEW RETIC HYDRANT FAILURE',
      operationDescription: 'WRCV0056 IM Capital Retic Wtr',
      basicStartDate: '25/08/2020',
      basicStartTime: '',
      basicFinishDate: '03/30/2021',
      basicFinishTime: '',
      dueDays: '217',
      customerWorkType: 'AC',
      customerPriority: 'A4',
      firstName: 'Ben',
      lastName: 'Brown',
      city: 'SOUTH BRISBANE',
      street: '66 MERIVALE ST',
      asset: 'AU-QUU-SOTH-4101',
      assetDescription: '',
      operationWorkCenter: '002CWI01',
      workCenterDescription: '',
      plannerGroup: '002',
      plannerGroupDescription: '',
      workOrderNotes: '',
      operationNotes: '',
      operationUserStatus: 'DISP',
      operationSubStatus: '',
      requiredStartDate: '25/08/2020',
      requiredStartTime: '',
      requiredFinishDate: '03/30/2021',
      requiredFinishTime: '',
      duration: '217',
      crewAllocation: '13057228',
      crewAllocationDescription: '',
      leadAllocation: '',
      leadAllocationDescription: '',
      scopingCrew: '',
      scopingCrewDescription: '',
      planningNotes: '',
      fieldNotes: '',
      shutPlanCode: '',
      shutPlanCodeDescription: '',
      bundleName: '',
      bundleDescription: '',
      onHoldReasonCode: '',
      onHoldReasonCodeDescription: '',
      rejectReasonCode: '',
      rejectReasonCodeDescription: '',
      permit: '',
      dials: '',
      vacTruck: '',
      GPR: '',
      trafficControl: '',
      plantNumber: 'RHY63551',
      subContractor: '',
      conflicts: false
    }
  ];
}
